### ISSUE TITLE
5. Oceanfront - Calendar: use section styles, non-transparent headers

### ISSUE THREAD

**Issue by alexivanenko** [1CRM/oceanfront#145]

**Comment by andrewwhitehead** [comment]
It looks like the header section doesn't apply to the basic Oceanfront calendar, so this might be more of an app-js issue. I think that the default style for the very top and left columns in the calendar should probably have a semi-transparent or opaque background (Mon/Tue/22/23 here, as well as the corner):

<img width="400" alt="Screen Shot 2022-06-23 at 16 26 09" src="https://user-images.githubusercontent.com/10636507/175431051-a8b9dab6-752d-4ab9-980a-c83fef339490.png">

**Comment by gansroy** [comment]
I guess this is okay to have a default BG for X and Y on the oceanfront.

Before:
https://disk.yandex.ru/i/qU-tEQvuofoAKw

After:
https://disk.yandex.ru/i/8Lhy9v2R1x9Veg
