### ISSUE TITLE
6. Oceanfront - Relative density values for input controls, ie. +1 or -2 compared to the default density

### ISSUE THREAD

**Issue by alexivanenko** [1CRM/oceanfront#146]

**Comment by andrewwhitehead** [comment]
This is meant to allow controls to adjust based on the inherited density setting, so for example line items in the tally might be +1 density (density 3 if the inherited/default value is 2). I'm not sure yet whether it makes more sense to reuse the `density` parameter or add a separate `relativeDensity` parameter.
