### ISSUE TITLE
Adjust alignment and padding on all input fields

### ISSUE THREAD

**Issue by markus-raffler** [1CRM/oceanfront#207]
Setting the density to 1 instead the current default value 2, combined with small adjustments on alignment and padding, results in a more balanced and cleaner look&feel. 

### Current state in Oceanfront:
![input_fields_oceanfront](https://user-images.githubusercontent.com/87305870/203523124-58eae9a2-fbb5-4d7f-8873-945cbd550da5.png)

### Proposal:
![input_fields_oceanfront_lines](https://user-images.githubusercontent.com/87305870/203523466-748a5592-f0b7-47b8-abfe-4d00602c56db.png)
![input_fields_adjusted](https://user-images.githubusercontent.com/87305870/203523476-8dfeb96d-6466-4780-8adb-58666f361440.png)

### Related Links:

- [Material Design 3 specs for filled text field layout](https://m3.material.io/components/text-fields/specs#8c032848-e442-46df-b25d-28f1315f234b)
- [Material Design 3 specs for outlined text field layout](https://m3.material.io/components/text-fields/specs#3a56b7a8-3a45-4d27-b95a-644fe38864e1 )

**Comment by alexivanenko** [comment]
Looks reasonable

**Comment by markus-raffler** [comment]
It may look like a minor complaint on an insignificant detail, but I assume a huge impact on the overall appearance. Thank you for the feedback!

**Comment by andrewwhitehead** [comment]
I will be revisiting the padding shortly, the measurements seem a little clearer in the version 3 specs. I don't think density 1 is going to be appropriate in a complex form but it could be the default for this library.

**Comment by alexivanenko** [comment]
@andrewwhitehead so what should we do with this one?

**Comment by ZakLilley** [comment]
@alexivanenko maybe have this job pre-selected for next sprint :)

**Comment by alexivanenko** [comment]
@ZakLilley as I remember Andrew had some doubts about this one

**Comment by ZakLilley** [comment]
@andrewwhitehead

**Comment by ZakLilley** [comment]
https://m3.material.io/components/text-fields/specs



![Image](https://github.com/1CRM/oceanfront/assets/95704919/51d5a24d-07db-4de1-9ebd-aedcf6945f56)
![Image](https://github.com/1CRM/oceanfront/assets/95704919/ebb61fe7-e1ab-4b56-b794-ec07984e5ec5)
![Image](https://github.com/1CRM/oceanfront/assets/95704919/c9610030-3f2c-4bd2-b670-e03b545a7a36)
![Image](https://github.com/1CRM/oceanfront/assets/95704919/b7c96710-7340-48e0-bd83-d50b8bf054de)

Cheers @alexivanenko

**Comment by alexivanenko** [comment]
@ZakLilley thank you, I think this one is good for @razinabrahamyan I'll schedule it for the next sprint.
