### ISSUE TITLE
Resize the arrow icon in select inputs

### ISSUE THREAD

**Issue by markus-raffler** [1CRM/oceanfront#208]
UPD: use this small icon in Buttons with items, in DataTable for sort indicators, in pagination for the popup opener  

--------------------------------------------------------------------------------------------
The arrow icon is currently too big. Scaling it a bit down results in a more balanced look.

### Current state in Oceanfront:
![select_fields_oceanfront](https://user-images.githubusercontent.com/87305870/203524800-5a6aac9a-84e5-4afe-ad35-9493760c803e.png)

### Material Design 3 specs:
![select_fields_m3](https://user-images.githubusercontent.com/87305870/203524991-005fff7e-4e47-40a9-aa2d-9f9dc42f0428.png)

### Proposal:
![select_fields_adjusted](https://user-images.githubusercontent.com/87305870/203525104-c9000b94-2f72-41a5-bf10-5587633d33bf.png)

### Related Links:
- [Select field component in vuetify](https://vuetifyjs.com/en/components/selects/)

**Comment by ZakLilley** [comment]
@andrewwhitehead I think we are agreed on this one?

**Comment by alexivanenko** [comment]
Agree, we will do it.

**Comment by brafreider** [comment]
@andrewwhitehead in my opinion, at least for 1CRM 9 this might be reopened. We missed to mention ref-fields, multi-buttons, sort indicators in list views and other appearences of this arrow icon.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/43208300/227925463-67363e9d-efd0-4578-a320-dfbb00e4ef01.png">

Cheers,
Björn
