### ISSUE TITLE
Display toggle fields without outline or background

### ISSUE THREAD

**Issue by markus-raffler** [1CRM/oceanfront#209]
Removing the background and outline from the toggle fields results in a cleaner look.

### Current state in Oceanfront:
![toggle_fields_oceanfront](https://user-images.githubusercontent.com/87305870/203526678-eeb5b487-4481-4258-b0c6-64714d43a23b.png)

### Proposal:
![toggle_fields_adjusted](https://user-images.githubusercontent.com/87305870/203526709-9334cf8c-d51c-4c78-9148-3917b221ae75.png)

### Related Links:
- [Checkbox component in vuetify](https://vuetifyjs.com/en/components/checkboxes/ )
- [Switch component in vuetify](https://vuetifyjs.com/en/components/switches/ )

**Comment by alexivanenko** [comment]
We will check this. I agree that it looks better without outline.

**Comment by andrewwhitehead** [comment]
I'm currently planning to make this border style an attribute of the field type which can be overridden, but defaults to invisible for certain field types like the checkbox and slider. I think in some contexts it may be more appropriate to keep the border.
