### ISSUE TITLE
Display slider input without lines and padding

### ISSUE THREAD

**Issue by markus-raffler** [1CRM/oceanfront#210]
Removing the background and outline from the slider inputs results in a cleaner look.

### Current state in Oceanfront:
![slider_input_oceanfront](https://user-images.githubusercontent.com/87305870/203528189-cf041350-8326-4749-b525-62932d83db5f.png)

### Proposal:
![slider_input_adjusted](https://user-images.githubusercontent.com/87305870/203528203-b1e13774-7062-4dce-92af-73dc89b37a9c.png)

**Comment by ZakLilley** [comment]
@andrewwhitehead I like this - if possible.

**Comment by alexivanenko** [comment]
I like it too, we have to apply it.

**Comment by andrewwhitehead** [comment]
Closed by #248
