### ISSUE TITLE
Implement the M3 specs for slider inputs to optimize usability and design

### ISSUE THREAD

**Issue by markus-raffler** [1CRM/oceanfront#211]
The M3 specs for slider inputs describe some interesting refinements:
-	A different color for the active track
-	A label, that becomes visible, when the slider is dragged
-	A state layer behind a slightly larger handle to optimize usability

Can you adapt them in oceanfront?

### Sliders in Material Design 3:
![slider_input_m3](https://user-images.githubusercontent.com/87305870/203529036-afdf58d3-478a-41d0-8207-65c7fa3b765c.png)

### Related Links:

- [Material Design 3 specs for sliders](https://m3.material.io/components/sliders/specs#e061929c-6aba-4938-ab23-0d24dc8d02c5 )
- [Material Design 3 specs for slider states](https://m3.material.io/components/sliders/specs#c3fb77a8-23b4-4eb0-8010-5950fb2a436b )

**Comment by ZakLilley** [comment]
@andrewwhitehead is this possible? Do we like it?

**Comment by gansroy** [comment]
Estimated points:2
factical points : 5

Reason:  Additional bugs in safari, design discussion, existed bugs fixes.
