### ISSUE TITLE
Extend HTML Editor - Add an ability to upload the image

### ISSUE THREAD

**Issue by alexivanenko** [1CRM/oceanfront#232]
Right now we can add an image only by URL but we need an ability to upload it.

**Comment by ZakLilley** [comment]
The ability to upload an image would be nice, rather than relying on a URL.

**Comment by mjrwhitehead** [comment]
Same for an image in background of a theme preset. Cheers - Michael Whitehead1CRM Systems ***@***.*** Falkland Road | Victoria, BC | Canada V8S 4L5On May 17, 2023, at 10:48 AM, Zak Dauncey-Lilley ***@***.***> wrote:﻿
The ability to upload an image would be nice, rather than relying on a URL.

**Comment by alexivanenko** [comment]
@ZakLilley yes I think we have to do it finally
@mjrwhitehead already added the task about the background image upload, it's even in the current sprint :)

**Comment by Anumzubair** [comment]
Works fine.
