### ISSUE TITLE
General: Popup -  Positioning issue

### ISSUE THREAD

**Issue by alexivanenko** [1CRM/oceanfront#365]
We have to fix this in oceanfront. 

From Andrey: "There is a long standing annoying issue with popup positioning. If you hover a link, additional details popup is displayed. If that link happens to be close to the bottom of the screen, the popup is not sized properly and does not fit the content, and there is a scroll bar in the popup. This also affects inputs that use popups, such as dropdowns and calendar"

https://github.com/1CRM/oceanfront/assets/5743284/de5b828f-2056-41d8-bb15-e8dc93817adc

https://github.com/1CRM/oceanfront/assets/5743284/b4dd0119-5e52-4c91-a953-03d8a5a0bbee

**Comment by Anumzubair** [comment]
It is still the same as the videos shown above.

**Comment by alexivanenko** [comment]
> It is still the same as the videos shown above.

works perfect as I see

https://github.com/1CRM/oceanfront/assets/5743284/2850b65b-6567-4c3b-8487-e251cdc5bccf

**Comment by Anumzubair** [comment]
> > It is still the same as the videos shown above.
> 
> works perfect as I see
> 
>  2024-06-04.09.14.04.mov

Yes, it works as shown in this video.
