### ISSUE TITLE
General: Split and Menu Buttons - Options shouldn't be selected (highlighted) 

### ISSUE THREAD

**Issue by alexivanenko** [1CRM/oceanfront#380]
I think this one should be resolved in oceanfornt.

<img width="525" alt="Снимок экрана 2024-04-08 в 08 14 05" src="https://github.com/1CRM/oceanfront/assets/5743284/de21e16f-d73f-4af0-8150-7f55ff8314cd">
<img width="478" alt="Снимок экрана 2024-04-08 в 08 19 25" src="https://github.com/1CRM/oceanfront/assets/5743284/40e4e911-f8d8-49c5-833a-4b83168e6a07">
<img width="468" alt="Снимок экрана 2024-04-08 в 08 19 36" src="https://github.com/1CRM/oceanfront/assets/5743284/0e6624cd-8de5-453f-9cef-63b0b3a2336d">

**Comment by Anumzubair** [comment]
It looks fine.
