### ISSUE TITLE
Select Input: Hide the options popup on pointer out after some delay 

### ISSUE THREAD

**Issue by alexivanenko** [1CRM/oceanfront#381]
https://github.com/1CRM/oceanfront/assets/5743284/a6e49de2-e3d8-446c-ab3b-e3d386ebfd0e
https://github.com/1CRM/oceanfront/assets/5743284/a2f0464c-7937-4a64-8619-8c67bf5b994b

**Comment by Anumzubair** [comment]
This popup appears to happen on a scroll but for a very short span.

![Image](https://github.com/1CRM/oceanfront/assets/135660781/6f4655d3-8fa5-4db9-b80e-17a5d896c393)

**Comment by alexivanenko** [comment]
> This popup appears to happen on a scroll but for a very short span.
> 
> ![Image](https://private-user-images.githubusercontent.com/135660781/326552285-6f4655d3-8fa5-4db9-b80e-17a5d896c393.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTY5NTQsIm5iZiI6MTcxNDQxNjY1NCwicGF0aCI6Ii8xMzU2NjA3ODEvMzI2NTUyMjg1LTZmNDY1NWQzLThmYTUtNGRiOS1iODBlLTE3YTVkODk2YzM5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQxODUwNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTk4OTM1ZDBkZTA2NGM3MzllZTFlYTY1MGFjMDgzMzNjN2Q0ZTAyMjA1YzFlMjAwYjRkNzlhMTIxMGY0ZmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wywwp_X6kP_ZAor4QifEqKJoaU62rBOsdzjpMo-VajE)

sorry. don't understand what do you mean
