### ISSUE TITLE
Toggle Input: Increase padding between the label and the switcher when the label in a frame

### ISSUE THREAD

**Issue by alexivanenko** [1CRM/oceanfront#432]
<img width="1414" alt="Снимок экрана 2024-09-25 в 12 22 40" src="https://github.com/user-attachments/assets/340dea2d-9258-429e-9a1e-bf8cc030f5a1">
<img width="757" alt="Снимок экрана 2024-09-25 в 12 23 02" src="https://github.com/user-attachments/assets/e579a13a-9aff-428a-8a55-359ab4fcfc67">
<img width="1062" alt="Снимок экрана 2024-09-25 в 12 23 27" src="https://github.com/user-attachments/assets/92ca8747-447b-439c-92ab-232e1cc8f158">
<img width="312" alt="Снимок экрана 2024-09-25 в 15 18 40" src="https://github.com/user-attachments/assets/f99abb4a-fdcd-49a0-9d94-738c27c01c6d">

**Comment by Anumzubair** [comment]
Looks fine.
